### ISSUE TITLE
Revolution Slider - Explosion Graphic on Homepage

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#10]
Implement animations for the exploded heat pump as per screenshot.
![Screenshot 2023-01-13 at 10 52 40](https://user-images.githubusercontent.com/1872195/212290874-bdd07dc3-b470-44a2-9802-bedd561cb6ec.png)

**Comment by meryllblanchet** [comment]
`rev-slider` plugin in the current Wordpress implementation.
