### ISSUE TITLE
Dark Section Text Size Increase

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#119]
This text should be increased in font size. See the original version.

![image (3)](https://user-images.githubusercontent.com/1872195/218029677-6771b159-b8f6-4d29-8305-fdef3b4f5952.png)
![image (4)](https://user-images.githubusercontent.com/1872195/218029691-c817949b-581c-411e-bcf8-0eb406c6f2d2.png)

**Comment by cuzuco2** [comment]
We just needed to change the text to h3 in the index page
