### ISSUE TITLE
iLightbox - Youtube Overlay Player

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#12]
This could probably be a generic feature. Think about how to represent in content. 

![Screenshot 2023-01-13 at 10 54 54](https://user-images.githubusercontent.com/1872195/212291360-08d24faf-4bed-4398-8869-07fb3d6629d3.png)
![Screenshot 2023-01-13 at 10 54 58](https://user-images.githubusercontent.com/1872195/212291376-a9f13eca-eb01-48c3-a22d-fdb5f8c84a52.png)

**Comment by solaris007** [comment]
Check the video embed component in the Franklin block collection.

https://github.com/adobe/helix-block-collection/blob/main/blocks/embed/

**Comment by solaris007** [comment]
Only load the video when the user clicks on it to improve LHS.

**Comment by meryllblanchet** [comment]
Called `iLightbox` in the current wordpress implementation.
