### ISSUE TITLE
Design Error Dark Columns

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#129]
FR Version- Homepage. This part is missing a text. Plus the technical info are not correctly sized and aligned as the original.And at the bottom there should be two section as the original. In general this one has completely to be readjusted as the original
![image (17)](https://user-images.githubusercontent.com/1872195/218036028-b9d1de23-356a-4c7a-9fd9-abe2ca9f5c0b.png)
![image (16)](https://user-images.githubusercontent.com/1872195/218036031-8ce24329-3d1c-40ab-893d-e66caa1267a5.png)

**Comment by cuzuco2** [comment]
Fixed by editing index.doc in french
