### ISSUE TITLE
iLightBox - Image Viewer

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#13]
Example: https://aerotop-sg.com/technische-daten/
Example with previous/next within section: https://aerotop-sg.com/storys/

May be available in the Franklin block collection.

Only load on click to improve LHS.

**Comment by meryllblanchet** [comment]
Seems to be the same `iLightbox` component than for the YT video in the current wordpress implementation.

**Comment by meryllblanchet** [comment]
We should carefully check with the practitioners:

On https://aerotop-sg.com/technische-daten/, it is the same `iLightbox` plugin than the YoutTube video.
For this use-case, can be consolidated with #12 .

On https://aerotop-sg.com/storys/, it is another plugin called `Fancybox`, with different behavior (slideshow) but also UX than `iLightbox` when there's a single image. For this use-case, please see #21 .
