### ISSUE TITLE
Cookie Consent Dialog

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#14]
Original site uses https://www.cookieyes.com/product/cookie-consent/

![Screenshot 2023-01-24 at 07 55 47](https://user-images.githubusercontent.com/1872195/214230145-48f8e1e9-b1a9-41d7-a8f9-373aaf0e5598.png)
![Screenshot 2023-01-24 at 07 55 54](https://user-images.githubusercontent.com/1872195/214230144-869dc89a-e98d-4807-b5a9-690d44901eb9.png)
![Screenshot 2023-01-24 at 07 56 03](https://user-images.githubusercontent.com/1872195/214230139-500c5466-c99e-42f4-9f5f-f5a66fbd02d5.png)

**Comment by solaris007** [comment]
cookie consent has no license for commercial use, paid plan: https://medium.com/sandstreamdev/gdpr-compliant-cookie-consent-f6655fa1b5af

**Comment by solaris007** [comment]
internationalization: use the [placeholders](https://www.hlx.live/docs/placeholders). The [fetchPlaceholders](https://github.com/adobe/helix-project-boilerplate/blob/main/scripts/lib-franklin.js#L155) function accepts a prefix parameter which would be your locale (see [example](https://github.com/hlxsites/airlessco/blob/34f4ee2f0929f67ad28c397389e07fa8e56f955b/blocks/product-comparison/product-comparison.js#L43-L44)).

**Comment by solaris007** [comment]
with customer consent, trying this library first: https://github.com/sandstreamdev/cookieconsent

**Comment by solaris007** [comment]
Added german translations for cookie consent:

![Screenshot 2023-01-24 at 13 50 39](https://user-images.githubusercontent.com/1872195/214296142-8e77ee71-d3b4-47dd-9b39-642921a985b6.png)

**Comment by ekremney** [comment]
A few comments:

- Dialog box doesn't close when I click on the text "Zustimmen"
- After I click on "Zustimmen" I do not see anything saved in none of the local/session storages or cookie
- Design of the consent dialog doesn't look like the original one
