### ISSUE TITLE
Navbar Appears Delayed

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#44]
When loading the site for the first time or reloading, the navigation appears only delayed. See attached video. The navigation should appear instantaneously basically to not block the user from making a choice.

https://user-images.githubusercontent.com/1872195/214519673-167158b8-b798-4fbb-b8a6-a6409e55d1b0.mov

**Comment by meryllblanchet** [comment]
Closing as no direct impact on LHS.
