### ISSUE TITLE
Cookie policy dialog does not close when text is clicked and responsiveness problem

### ISSUE THREAD

**Issue by ekremney** [hlxsites/elco-aerotop-sg#47]
- Cookie policy dialog does not close when text is clicked
- Texts on the buttons does not scale responsively in mobile mode

**Comment by dzehnder** [comment]
I cannot reproduce those issues on iPhone 14 with Chrome and Safari, as well as on Mac with Safari using iOS user agent and Chrome in device emulator.

**Comment by ekremney** [comment]
this one got solved by other PRs
