### ISSUE TITLE
Progress Bar: Numeric Horizontal Bar Chart

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#9]
Add dark / light bar chart renderings, possibly based on a table in the content with style dictated by the heard row. See Screenshots.
![Screenshot 2023-01-13 at 10 50 00](https://user-images.githubusercontent.com/1872195/212290368-2295984d-fec5-49b7-a42a-7c85b0f22c8f.png)
![Screenshot 2023-01-13 at 10 49 56](https://user-images.githubusercontent.com/1872195/212290379-da7c48a0-6754-40f0-ad57-b5255275d446.png)

**Comment by meryllblanchet** [comment]
The wp plugin is called `progress-bar`.
