### ISSUE TITLE
Hero Should Render Title Regularly

### ISSUE THREAD

**Issue by solaris007** [hlxsites/elco-aerotop-sg#92]
Original:
![Screenshot 2023-01-31 at 13 36 45](https://user-images.githubusercontent.com/1872195/215761698-dcccab74-ead0-49af-bccb-94681ab86e7c.png)

Now:
![Screenshot 2023-01-31 at 13 36 57](https://user-images.githubusercontent.com/1872195/215761744-a910f052-8321-4fdf-8a61-6938013642ce.png)

**Comment by cuzuco2** [comment]
The issue was with the original word file, in one page the title was part of the main image and on the other it was in the next section.
The former is what was causing the title to be rendered within the image.

**Comment by cuzuco2** [comment]
The issue was with the original word file, in one page the title was part of the main image and on the other it was in the next section.
The former is what was causing the title to be rendered within the image.
